apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hackbox
  namespace: default
  labels:
    k8s-app: hackbox
spec:
  selector:
    matchLabels:
      name: hackbox
  template:
    metadata:
      labels:
        name: hackbox
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
      containers:
      - name: hackbox
        image: goestin/hackbox
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        stdin: true
        tty: true
        command: ["/bin/bash"]
      terminationGracePeriodSeconds: 30






