apiVersion: v1
kind: Pod
metadata:
  name: hackbox
spec:
  #nodeName: k8s-node1
  containers:
  - name: hackbox
    image: goestin/hackbox:latest
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "512Mi"
    stdin: true
    tty: true
    command: ["/bin/bash"]

