apiVersion: v1
kind: Pod
metadata:
  name: hackbox
spec:
  containers:
  - name: hackbox
    image: ghcr.io/jzandbergen/hackbox:v0.1.5
    securityContext:
      privileged: True
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "512Mi"
    stdin: true
    tty: true
    command: ["/bin/bash"]

